packages:
  - packages/*
  - apps/*
catalog:
  '@antfu/eslint-config': ^4.12.0
  '@iconify/vue': ^4.3.0
  '@rushstack/eslint-patch': ^1.11.0
  '@tsconfig/node20': ^20.1.5
  '@types/node': ^22.14.1
  '@typescript-eslint/eslint-plugin': ^8.30.1
  '@typescript-eslint/parser': ^8.30.1
  '@unocss/core': 66.1.0-beta.6
  '@unocss/preset-mini': 66.1.0-beta.6
  '@unocss/transformer-variant-group': 66.1.0-beta.6
  '@vitejs/plugin-vue': ^5.2.3
  '@vue/eslint-config-prettier': 10.2.0
  '@vue/eslint-config-typescript': 14.5.0
  '@vue/tsconfig': ^0.7.0
  '@vueuse/components': 13.1.0
  '@vueuse/core': 13.1.0
  colord: ^2.9.3
  eslint: 9.24.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-vue: 10.0.0
  gsap: ^3.12.7
  gsap-trial: ^3.12.7
  npm-run-all2: 7.0.2
  prettier: ^3.5.3
  reka-ui: 2.2.0
  sass: ^1.86.3
  typescript: ~5.8.3
  unocss: 66.1.0-beta.6
  vite: 6.1.1
  vite-plugin-dts: ^4.5.3
  vite-plugin-vue-devtools: ^7.7.2
  vue-router: '4'
  vue-sonner: ^1.3.2
  vue-tsc: ^2.2.8
catalogs:
  conflicts_vite_6_3_0:
    vite: 6.3.0
