packages:
  - packages/*
  - apps/*

catalog:
  '@antfu/eslint-config': ^4.16.1
  '@floating-ui/vue': ^1.1.6
  '@iconify-json/pixelarticons': ^1.2.2
  '@iconify/vue': ^4.3.0
  '@monaco-editor/loader': ^1.5.0
  '@nuxt/content': ^3.6.1
  '@nuxt/eslint': 1.4.1
  '@nuxt/eslint-config': 1.4.1
  '@nuxt/icon': 1.14.0
  '@nuxt/image': 1.10.0
  '@nuxthub/core': ^0.9.0
  '@nuxtjs/mdc': 0.17.0
  '@nuxtlabs/monarch-mdc': ^0.8.0
  '@paralleldrive/cuid2': ^2.2.2
  '@pinia/nuxt': 0.11.1
  '@rushstack/eslint-patch': ^1.11.0
  '@tiptap/core': ^2.22.3
  '@tiptap/extension-bold': ^2.22.3
  '@tiptap/extension-character-count': ^2.22.3
  '@tiptap/extension-document': ^2.22.3
  '@tiptap/extension-heading': ^2.22.3
  '@tiptap/extension-history': ^2.22.3
  '@tiptap/extension-italic': ^2.22.3
  '@tiptap/extension-paragraph': ^2.22.3
  '@tiptap/extension-placeholder': ^2.22.3
  '@tiptap/extension-text': ^2.22.3
  '@tiptap/pm': ^2.22.3
  '@tiptap/starter-kit': ^2.22.3
  '@tiptap/suggestion': ^2.22.3
  '@tiptap/vue-3': ^2.22.3
  '@tsconfig/node20': ^20.1.5
  '@types/hast': ^3.0.4
  '@types/mdast': ^4.0.4
  '@types/node': ^22.14.1
  '@typescript-eslint/eslint-plugin': ^8.30.1
  '@typescript-eslint/parser': ^8.30.1
  '@umbrajs/core': ^0.0.456
  '@unovis/ts': ^1.5.1
  '@unovis/vue': ^1.5.1
  '@vitejs/plugin-vue': ^5.2.3
  '@vue/eslint-config-prettier': 10.2.0
  '@vue/eslint-config-typescript': 14.5.0
  '@vue/tsconfig': ^0.7.0
  '@vueuse/components': 13.4.0
  '@vueuse/core': 13.4.0
  '@vueuse/nuxt': 13.4.0
  '@webgpu/types': ^0.1.48
  better-auth: ^1.2.10
  better-sqlite3: ^12.2.0
  destr: ^2.0.5
  drizzle-kit: ^0.31.2
  drizzle-orm: ^0.44.2
  eslint: ^9.29.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-vue: 10.0.0
  github-slugger: ^2.0.0
  gl-matrix: ^3.4.3
  gsap: ^3.13.0
  hast: ^1.0.0
  hast-util-format: ^1.1.0
  hast-util-to-html: ^9.0.5
  hast-util-to-mdast: ^10.1.2
  hast-util-to-string: ^3.0.1
  mdast: ^3.0.0
  nearest-color: ^0.4.4
  npm-run-all: ^4.1.5
  npm-run-all2: 7.0.2
  nuxt: ^3.17.5
  nuxt-time: 1.0.3
  pinia: 3.0.3
  prettier: ^3.5.3
  property-information: ^7.1.0
  rehype: ^13.0.2
  rehype-raw: ^7.0.0
  rehype-stringify: ^10.0.1
  reka-ui: 2.2.0
  remark-gfm: ^4.0.1
  remark-mdc: ^3.6.0
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.2
  remark-stringify: ^11.0.0
  sass: ^1.89.2
  scule: ^1.3.0
  shiki: ^3.7.0
  temporal-polyfill: ^0.3.0
  tippy.js: ^6.3.7
  typescript: ^5.8.3
  ufo: ^1.6.1
  unified: ^11.0.5
  unist-util-visit: ^5.0.0
  vaul-vue: ^0.4.1
  vfile: ^6.0.3
  vite: 6.3.1
  vite-plugin-dts: ^4.5.3
  vite-plugin-glsl: ^1.3.0
  vite-plugin-vue-devtools: ^7.7.5
  vitest: ^3.1.3
  vue: ^3.5.17
  vue-router: ^4.5.1
  vue-sonner: ^1.3.2
  vue-tsc: ^2.2.10
  wrangler: 4.22.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - maplibre-gl
  - sharp
  - unrs-resolver
  - workerd
catalogs:
  conflicts_vue_h3_5_11:
    vue: ^3.5.11
  conflicts_vue-router_h4_4_5:
    vue-router: ^4.4.5
  conflicts_@rushstack/eslint-patch_h1_10_4:
    '@rushstack/eslint-patch': ^1.10.4
  conflicts_@tsconfig/node20_h20_1_4:
    '@tsconfig/node20': ^20.1.4
  conflicts_@types/node_h22_7_5:
    '@types/node': ^22.7.5
  conflicts_@vitejs/plugin-vue_h5_1_4:
    '@vitejs/plugin-vue': ^5.1.4
  conflicts_@vue/eslint-config-prettier_h10_0_0:
    '@vue/eslint-config-prettier': ^10.0.0
  conflicts_@vue/eslint-config-typescript_h14_0_0:
    '@vue/eslint-config-typescript': ^14.0.0
  conflicts_@vue/tsconfig_h0_5_1:
    '@vue/tsconfig': ^0.5.1
  conflicts_eslint_h9_12_0:
    eslint: ^9.12.0
  conflicts_eslint-plugin-vue_h9_28_0:
    eslint-plugin-vue: ^9.28.0
  conflicts_npm-run-all2_h6_2_3:
    npm-run-all2: ^6.2.3
  conflicts_prettier_h3_3_3:
    prettier: ^3.3.3
  conflicts_typescript_t5_6_2:
    typescript: ~5.6.2
  conflicts_vite_h5_4_8:
    vite: ^5.4.8
  conflicts_vite-plugin-vue-devtools_h7_4_6:
    vite-plugin-vue-devtools: ^7.4.6
  conflicts_vue-tsc_h2_1_6:
    vue-tsc: ^2.1.6
