packages:
  - packages/*
  - apps/*

catalog:
  '@antfu/eslint-config': ^4.12.0
  '@floating-ui/vue': ^1.1.6
  '@iconify-json/pixelarticons': ^1.2.2
  '@iconify/vue': ^4.3.0
  '@monaco-editor/loader': ^1.5.0
  '@nuxt/content': ^3.4.0
  '@nuxt/eslint': 1.3.0
  '@nuxt/eslint-config': 1.3.0
  '@nuxt/icon': 1.12.0
  '@nuxt/image': 1.9.0
  '@nuxthub/core': ^0.8.24
  '@nuxtjs/mdc': 0.16.1
  '@nuxtlabs/monarch-mdc': ^0.5.0
  '@paralleldrive/cuid2': ^2.2.2
  '@pinia/nuxt': 0.11.0
  '@rushstack/eslint-patch': ^1.11.0
  '@tiptap/core': ^2.11.5
  '@tiptap/extension-bold': ^2.11.5
  '@tiptap/extension-character-count': ^2.11.5
  '@tiptap/extension-document': ^2.11.5
  '@tiptap/extension-heading': ^2.11.5
  '@tiptap/extension-history': ^2.11.5
  '@tiptap/extension-italic': ^2.11.5
  '@tiptap/extension-paragraph': ^2.11.5
  '@tiptap/extension-placeholder': ^2.11.5
  '@tiptap/extension-text': ^2.11.5
  '@tiptap/pm': ^2.11.5
  '@tiptap/starter-kit': ^2.11.5
  '@tiptap/suggestion': ^2.11.5
  '@tiptap/vue-3': ^2.11.5
  '@tsconfig/node20': ^20.1.5
  '@types/hast': ^3.0.4
  '@types/mdast': ^4.0.4
  '@types/node': ^22.14.1
  '@typescript-eslint/eslint-plugin': ^8.30.1
  '@typescript-eslint/parser': ^8.30.1
  '@umbrajs/core': ^0.0.456
  '@unocss/core': 66.1.0-beta.6
  '@unocss/nuxt': 66.1.0-beta.6
  '@unocss/preset-mini': 66.1.0-beta.6
  '@unocss/transformer-variant-group': 66.1.0-beta.6
  '@unovis/ts': ^1.5.1
  '@unovis/vue': ^1.5.1
  '@vitejs/plugin-vue': ^5.2.3
  '@vue/eslint-config-prettier': 10.2.0
  '@vue/eslint-config-typescript': 14.5.0
  '@vue/tsconfig': ^0.7.0
  '@vueuse/components': 13.1.0
  '@vueuse/core': 13.1.0
  '@vueuse/nuxt': 13.1.0
  apca-w3: ^0.1.9
  better-auth: ^1.2.7
  colord: ^2.9.3
  colorparsley: ^0.1.8
  destr: ^2.0.5
  drizzle-kit: ^0.31.0
  drizzle-orm: ^0.42.0
  eslint: 9.24.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-vue: 10.0.0
  github-slugger: ^2.0.0
  gsap: ^3.12.7
  gsap-trial: ^3.12.7
  hast: ^1.0.0
  hast-util-format: ^1.1.0
  hast-util-to-html: ^9.0.5
  hast-util-to-mdast: ^10.1.2
  hast-util-to-string: ^3.0.1
  mdast: ^3.0.0
  nearest-color: ^0.4.4
  npm-run-all: ^4.1.5
  npm-run-all2: 7.0.2
  nuxt: ^3.16.2
  nuxt-time: 1.0.3
  pinia: 3.0.1
  prettier: ^3.5.3
  property-information: ^7.0.0
  rehype: ^13.0.2
  rehype-raw: ^7.0.0
  rehype-stringify: ^10.0.1
  reka-ui: 2.2.0
  remark-gfm: ^4.0.1
  remark-mdc: ^3.5.3
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.2
  remark-stringify: ^11.0.0
  sass: ^1.86.3
  scule: ^1.3.0
  shiki: ^3.2.2
  temporal-polyfill: ^0.3.0
  tippy.js: ^6.3.7
  typescript: ~5.8.3
  ufo: ^1.6.1
  unified: ^11.0.5
  unist-util-visit: ^5.0.0
  unocss: 66.1.0-beta.6
  vfile: ^6.0.3
  vite: 6.3.1
  vite-plugin-dts: ^4.5.3
  vite-plugin-vue-devtools: ^7.7.5
  vitest: ^3.1.3
  vue: ^3.5.13
  vue-router: '4'
  vue-sonner: ^1.3.2
  vue-tsc: ^2.2.8
  wrangler: 4.12.0

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - vue-demi
  - workerd

catalogs:
  conflicts_gsap_h3_13_0:
    gsap: ^3.13.0
  conflicts_pinia_3_0_2:
    pinia: 3.0.2
  conflicts_vue-router_h4_5_1:
    vue-router: ^4.5.1
  conflicts_eslint_h9_26_0:
    eslint: ^9.26.0
  conflicts_typescript_h5_8_3:
    typescript: ^5.8.3
  conflicts_vue-tsc_h2_2_10:
    vue-tsc: ^2.2.10
  conflicts_@nuxt/image_1_10_0:
    '@nuxt/image': 1.10.0
  conflicts_@tiptap/core_h2_11_7:
    '@tiptap/core': ^2.11.7
  conflicts_@tiptap/extension-bold_h2_11_7:
    '@tiptap/extension-bold': ^2.11.7
  conflicts_@tiptap/extension-character-count_h2_11_7:
    '@tiptap/extension-character-count': ^2.11.7
  conflicts_@tiptap/extension-document_h2_11_7:
    '@tiptap/extension-document': ^2.11.7
  conflicts_@tiptap/extension-heading_h2_11_7:
    '@tiptap/extension-heading': ^2.11.7
  conflicts_@tiptap/extension-history_h2_11_7:
    '@tiptap/extension-history': ^2.11.7
  conflicts_@tiptap/extension-italic_h2_11_7:
    '@tiptap/extension-italic': ^2.11.7
  conflicts_@tiptap/extension-paragraph_h2_11_7:
    '@tiptap/extension-paragraph': ^2.11.7
  conflicts_@tiptap/extension-placeholder_h2_11_7:
    '@tiptap/extension-placeholder': ^2.11.7
  conflicts_@tiptap/extension-text_h2_11_7:
    '@tiptap/extension-text': ^2.11.7
  conflicts_@tiptap/pm_h2_11_7:
    '@tiptap/pm': ^2.11.7
  conflicts_@tiptap/starter-kit_h2_11_7:
    '@tiptap/starter-kit': ^2.11.7
  conflicts_@tiptap/vue-3_h2_11_7:
    '@tiptap/vue-3': ^2.11.7
  conflicts_@unocss/core_h66_1_0mbeta_6:
    '@unocss/core': ^66.1.0-beta.6
  conflicts_@unocss/transformer-variant-group_h66_1_0mbeta_6:
    '@unocss/transformer-variant-group': ^66.1.0-beta.6
  conflicts_vue-router_h4_5_0:
    vue-router: ^4.5.0
  conflicts_eslint_h9_24_0:
    eslint: ^9.24.0
  conflicts_unocss_h66_1_0mbeta_6:
    unocss: ^66.1.0-beta.6
  conflicts_@types/node_h22_13_4:
    '@types/node': ^22.13.4
  conflicts_typescript_h5_7_3:
    typescript: ^5.7.3
  conflicts_vite_6_1_1:
    vite: 6.1.1
  conflicts_vite-plugin-dts_h4_5_0:
    vite-plugin-dts: ^4.5.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - maplibre-gl
  - unrs-resolver
