packages:
  - packages/*
  - apps/*

catalog:
  '@antfu/eslint-config': ^4.12.0
  '@floating-ui/vue': ^1.1.6
  '@iconify/vue': ^4.3.0
  '@nuxt/image': 1.9.0
  '@rushstack/eslint-patch': ^1.11.0
  '@tiptap/core': ^2.11.5
  '@tiptap/extension-bold': ^2.11.5
  '@tiptap/extension-character-count': ^2.11.5
  '@tiptap/extension-document': ^2.11.5
  '@tiptap/extension-heading': ^2.11.5
  '@tiptap/extension-history': ^2.11.5
  '@tiptap/extension-italic': ^2.11.5
  '@tiptap/extension-paragraph': ^2.11.5
  '@tiptap/extension-placeholder': ^2.11.5
  '@tiptap/extension-text': ^2.11.5
  '@tiptap/pm': ^2.11.5
  '@tiptap/starter-kit': ^2.11.5
  '@tiptap/suggestion': ^2.11.5
  '@tiptap/vue-3': ^2.11.5
  '@tsconfig/node20': ^20.1.5
  '@types/node': ^22.14.1
  '@typescript-eslint/eslint-plugin': ^8.30.1
  '@typescript-eslint/parser': ^8.30.1
  '@umbrajs/core': ^0.0.456
  '@unocss/core': 66.1.0-beta.6
  '@unocss/preset-mini': 66.1.0-beta.6
  '@unocss/transformer-variant-group': 66.1.0-beta.6
  '@vitejs/plugin-vue': ^5.2.3
  '@vue/eslint-config-prettier': 10.2.0
  '@vue/eslint-config-typescript': 14.5.0
  '@vue/tsconfig': ^0.7.0
  '@vueuse/components': 13.1.0
  '@vueuse/core': 13.1.0
  apca-w3: ^0.1.9
  colord: ^2.9.3
  colorparsley: ^0.1.8
  eslint: 9.24.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-vue: 10.0.0
  gsap: ^3.12.7
  gsap-trial: ^3.12.7
  nearest-color: ^0.4.4
  npm-run-all: ^4.1.5
  npm-run-all2: 7.0.2
  pinia: 3.0.1
  prettier: ^3.5.3
  reka-ui: 2.2.0
  sass: ^1.86.3
  tippy.js: ^6.3.7
  typescript: ~5.8.3
  unocss: 66.1.0-beta.6
  vite: 6.3.1
  vite-plugin-dts: ^4.5.3
  vite-plugin-vue-devtools: ^7.7.5
  vue: ^3.5.13
  vue-router: '4'
  vue-sonner: ^1.3.2
  vue-tsc: ^2.2.8

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - vue-demi
  - workerd
