/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedServerRouteImport } from './routes/_authed/server'
import { Route as AuthedClientOnlyRouteImport } from './routes/_authed/client-only'
import { Route as AuthedClientOnlyIndexRouteImport } from './routes/_authed/client-only.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedServerRoute = AuthedServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientOnlyRoute = AuthedClientOnlyRouteImport.update({
  id: '/client-only',
  path: '/client-only',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientOnlyIndexRoute = AuthedClientOnlyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedClientOnlyRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/client-only': typeof AuthedClientOnlyRouteWithChildren
  '/server': typeof AuthedServerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/client-only/': typeof AuthedClientOnlyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/server': typeof AuthedServerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/client-only': typeof AuthedClientOnlyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/client-only': typeof AuthedClientOnlyRouteWithChildren
  '/_authed/server': typeof AuthedServerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/client-only/': typeof AuthedClientOnlyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/client-only'
    | '/server'
    | '/api/auth/$'
    | '/client-only/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/server'
    | '/api/auth/$'
    | '/client-only'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/client-only'
    | '/_authed/server'
    | '/api/auth/$'
    | '/_authed/client-only/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/server': {
      id: '/_authed/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof AuthedServerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/client-only': {
      id: '/_authed/client-only'
      path: '/client-only'
      fullPath: '/client-only'
      preLoaderRoute: typeof AuthedClientOnlyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/client-only/': {
      id: '/_authed/client-only/'
      path: '/'
      fullPath: '/client-only/'
      preLoaderRoute: typeof AuthedClientOnlyIndexRouteImport
      parentRoute: typeof AuthedClientOnlyRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedClientOnlyRouteChildren {
  AuthedClientOnlyIndexRoute: typeof AuthedClientOnlyIndexRoute
}

const AuthedClientOnlyRouteChildren: AuthedClientOnlyRouteChildren = {
  AuthedClientOnlyIndexRoute: AuthedClientOnlyIndexRoute,
}

const AuthedClientOnlyRouteWithChildren =
  AuthedClientOnlyRoute._addFileChildren(AuthedClientOnlyRouteChildren)

interface AuthedRouteChildren {
  AuthedClientOnlyRoute: typeof AuthedClientOnlyRouteWithChildren
  AuthedServerRoute: typeof AuthedServerRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedClientOnlyRoute: AuthedClientOnlyRouteWithChildren,
  AuthedServerRoute: AuthedServerRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
