/**
 * Sets up authentication for the Convex client
 * Uses the JWT token generated by the Better Auth Convex plugin
 */
export default defineNuxtPlugin({
  name: 'convex-auth',
  dependsOn: ['convue-client'],
  async setup() {
    const { useConvexClient } = await import('convue')
    const auth = useAuth()

    // Wait for client to be available
    const client = useConvexClient()

    // Set up auth token fetching for Convex
    client.setAuth(async () => {
      try {
        console.log('[convex-auth] Fetching auth token...')
        console.log('[convex-auth] isAuthenticated:', auth.isAuthenticated.value)

        if (!auth.isAuthenticated.value) {
          console.log('[convex-auth] User not authenticated')
          return null
        }

        // The session cookie is HttpOnly and can't be read by JavaScript
        // But it IS sent with HTTP requests to the same domain (localhost)
        // So we call our Nuxt proxy endpoint which forwards to Convex
        // The Nuxt proxy has access to the cookie and can include it in the request

        try {
          const response = await fetch('/api/auth/convex/token', {
            method: 'POST',
            credentials: 'include', // Include cookies in the request
            headers: {
              'Content-Type': 'application/json',
            },
          })

          if (!response.ok) {
            const error = await response.json()
            console.error('[convex-auth] Token endpoint error:', error)
            return null
          }

          const result = await response.json()
          console.log('[convex-auth] Token response:', result)

          const token = result?.data?.token
          console.log('[convex-auth] JWT token:', token)

          if (token) {
            console.log('[convex-auth] Successfully fetched JWT token, length:', token.length)
            // Decode JWT to see payload (without verification)
            try {
              const [_header, payload] = token.split('.')
              const decodedPayload = JSON.parse(atob(payload))
              console.log('[convex-auth] JWT payload:', decodedPayload)
            } catch (e) {
              console.warn('[convex-auth] Could not decode JWT:', e)
            }
            return token
          }

          console.warn('[convex-auth] No token in response:', result)
          return null
        } catch (error) {
          console.error('[convex-auth] Failed to fetch token:', error)
          return null
        }
      }
      catch (error) {
        console.error('[convex-auth] Failed to get auth token:', error)
        return null
      }
    })

    console.log('[convex-auth] Auth setup complete')
  },
})
